# Generated by Django 5.1.8 on 2025-04-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
